# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class EopHeader < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "v0.0.2-next"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jpbede/eop-header/releases/download/v0.0.2/eop-header_v0.0.2_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "1ae6497c0d8f57e56f82b42a02de7ed2af1842e1117c838bef3699e883d9f9f6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jpbede/eop-header/releases/download/v0.0.2/eop-header_v0.0.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
      sha256 "2703ffd7fb4577c7106bee9b6969dc2ead982317792a68fd5fd1e1068616ac10"
    end
  end

  def test
    system "#{bin}/program --version"
  end

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
