# This file was generated by GoReleaser. DO NOT EDIT.
class EopHeader < Formula
  desc "Little tool to decode Microsoft Exchange Online Protection header into a nice view and explains them"
  homepage "https://github.com/jpbede/eop-header"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jpbede/eop-header/releases/download/v0.0.3/eop-header_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "1d42edd4fd9bd8ba9a43cd4672f6cb32a07212928c3c3bbad9c5efa39896ff0f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jpbede/eop-header/releases/download/v0.0.3/eop-header_0.0.3_Linux_x86_64.tar.gz"
      sha256 "d983df96ad91fb757f81f6bcb85bb5ad57417b39b81120fb1ef885f6beaa9d44"
    end
  end

  def install
    bin.install "eop-header"
  end

  test do
    system "#{bin}/eop-header --version"
  end
end
