# This file was generated by GoReleaser. DO NOT EDIT.
class EopHeader < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "v0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jpbede/eop-header/releases/download/v0.0.2/eop-header_v0.0.2_Darwin_x86_64.tar.gz"
    sha256 "7438c50993f634779dc8e3cc41a3cb9076b6d4b4e47945d69ff685170fdb3bb6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jpbede/eop-header/releases/download/v0.0.2/eop-header_v0.0.2_Linux_x86_64.tar.gz"
      sha256 "b0df928f162168ce058663bfeffd01d91ec4cc6f1e1a5fc1e1c836efd4f38da9"
    end
  end

  def install
    bin.install "eop-header"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/eop-header --version"
  end
end
