# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LokiAuthProxy < Formula
  desc "Stateless Grafana Loki authentication proxy"
  homepage "https://github.com/jpbede/loki-auth-proxy"
  version "0.0.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.0.2/loki-auth-proxy_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "f232295c8d101c94192e6768d17d1431442ea2ee222fc2c02d99dd3c5a2a82b6"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.0.2/loki-auth-proxy_0.0.2_Darwin_arm64.tar.gz"
    sha256 "c4065caed7f1a3968f2744d6041beec6d2c97cec1884382d7b044da3a80a4357"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.0.2/loki-auth-proxy_0.0.2_Linux_x86_64.tar.gz"
    sha256 "8b19272225edd6ad81620d1076cccbcabe1ebdeb606eeb6510208a0a1275eab5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.0.2/loki-auth-proxy_0.0.2_Linux_arm64.tar.gz"
    sha256 "6adccb1ad76d80e7ee58d3516ddaeda05ffe0f23dc871b519a142d6cc1fd6ca4"
  end

  def install
    bin.install "loki-auth-proxy"
  end

  test do
    system "#{bin}/loki-auth-proxy"
  end
end
