# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LokiAuthProxy < Formula
  desc "Stateless Grafana Loki authentication proxy"
  homepage "https://github.com/jpbede/loki-auth-proxy"
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.2.0/loki-auth-proxy_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "2184a7917595998687178a6eb72fc6f73327c42cdba03c0c7dba395dab735c51"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.2.0/loki-auth-proxy_0.2.0_Darwin_arm64.tar.gz"
      sha256 "78dcfda563be71c1da2f92486e2fcb6d443d5238fa39e45a647a75c91a6c35db"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.2.0/loki-auth-proxy_0.2.0_Linux_x86_64.tar.gz"
      sha256 "b9fbea5aaa57eb384b4e21144835496f713c78eb882ba20fab2ea2973e2238bc"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpbede/loki-auth-proxy/releases/download/v0.2.0/loki-auth-proxy_0.2.0_Linux_arm64.tar.gz"
      sha256 "976b88252febbd0b759e02b96f8b9d4c36ea3df424e4ba5d14bb73957ff46a69"
    end
  end

  def install
    bin.install "loki-auth-proxy"
  end

  test do
    system "#{bin}/loki-auth-proxy"
  end
end
