# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ratiocheck < Formula
  desc "Microservice to check image to content ration of HTML pages"
  homepage "https://github.com/jpbede/ratiocheck"
  version "2022.7.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jpbede/ratiocheck/releases/download/2022.7.4/ratiocheck_2022.7.4_Darwin_arm64.tar.gz"
      sha256 "4cb568becb68216912ec474f12a747f749d1168d6dfb70acb6180d9cb058e6d2"

      def install
        bin.install "ratiocheck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jpbede/ratiocheck/releases/download/2022.7.4/ratiocheck_2022.7.4_Darwin_x86_64.tar.gz"
      sha256 "897f9e4ba4c6aa57b9b7e043e36c933077a5a6e9c666178bb574de3d400f5e03"

      def install
        bin.install "ratiocheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jpbede/ratiocheck/releases/download/2022.7.4/ratiocheck_2022.7.4_Linux_arm64.tar.gz"
      sha256 "808cad4c6636b9930bfebe027e1407236bacf32b92cffc6a0b00e43cf10bfa84"

      def install
        bin.install "ratiocheck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jpbede/ratiocheck/releases/download/2022.7.4/ratiocheck_2022.7.4_Linux_x86_64.tar.gz"
      sha256 "6ab3ac147f1c2c43c97a9a52e7bd15ffb6f09dee8496e45f4271d8d331f959f3"

      def install
        bin.install "ratiocheck"
      end
    end
  end

  test do
    system "#{bin}/ratiocheck"
  end
end
